"""Test player."""
import datetime
import uuid
from typing import AsyncGenerator

import pytest
from aioresponses import aioresponses

from asyncpixel import Hypixel
from asyncpixel.constants import GameType
from asyncpixel.models.players.bedwars import bedwars_level_from_exp
from asyncpixel.models.utils import safe_divide
from asyncpixel.utils import calc_player_level, validate_game_type

# from asyncpixel.models import gametype


@pytest.mark.asyncio
async def test_player_level_calc() -> None:
    """Test player level calc."""
    level = calc_player_level(514642.0)

    assert level == 18.090376392868585


@pytest.mark.asyncio
async def test_player(hypixel_client: AsyncGenerator[Hypixel, None], key: uuid.UUID) -> None:
    """Test to check the player method returns correct data."""
    with aioresponses() as m:
        m.get(
            f"https://api.hypixel.net/player?key={key!s}" + "&uuid=405dcf08-b80f-4e23-b97d-943ad93d14fd",
            status=200,
            headers={
                "RateLimit-Limit": "120",
                "RateLimit-Remaining": "119",
                "RateLimit-Reset": "8",
            },
            payload={
                "success": True,
                "player": {
                    "_id": "55e96b45de314c0f0424dc9a",
                    "uuid": "405dcf08b80f4e23b97d943ad93d14fd",
                    "firstLogin": 1441360709245,
                    "playername": "darkflame72",
                    "lastLogin": 1608016405945,
                    "displayname": "Darkflame72",
                    "knownAliases": ["MRL03", "Darkflame72"],
                    "socialMedia": {"links": {"Twitter": "https://twitter.com/hypixel"}},
                    "knownAliasesLower": ["mrl03", "darkflame72"],
                    "achievementsOneTime": [
                        "general_first_join",
                        "blitz_first_game",
                        "general_first_game",
                        "general_first_chat",
                        "vampirez_vampire_shop",
                        "vampirez_close_call",
                        "general_youtuber",
                        "bedwars_team_player",
                        "bedwars_builder",
                        "bedwars_pickaxe_challenge",
                        "bedwars_already_over",
                        "bedwars_survivor",
                        "bedwars_ultimate_defense",
                        "bedwars_emerald_hoarder",
                        "bedwars_first",
                        "bedwars_geared_up",
                        "bedwars_diamond_hoarder",
                        "bedwars_sniper",
                        "bedwars_dont_need_bed",
                        "skywars_max_perk",
                        "skywars_legendary",
                        "walls3_happy",
                        "walls3_find_chest",
                        "bedwars_its_dark_down_there",
                        "bedwars_thats_a_first",
                        "vampirez_purchase_armor",
                        "bedwars_buggy_beds",
                        "tntgames_bow_spleef_first_double_jump",
                        "murdermystery_soldiers_eliminated",
                        "bedwars_first_blood",
                        "general_first_party",
                        "easter_happy_easter_2019",
                        "housing_join_guild",
                        "bedwars_minefield",
                        "bedwars_savvy_shopper",
                        "bedwars_you_cant_do_that",
                        "general_first_friend",
                        "bedwars_katniss_everdeen_style",
                        "bedwars_rejoining_the_dream",
                        "bedwars_super_looter",
                        "blitz_safety_first",
                        "bedwars_strategist",
                        "bedwars_out_of_stock",
                        "bedwars_distraction",
                        "general_creeperbook",
                        "arcade_pig_fishing_super_bacon",
                        "arcade_professional_mower",
                        "bedwars_shear_luck",
                        "copsandcrims_late_to_the_party",
                        "copsandcrims_sneak_kill",
                        "bedwars_destroy_beds",
                        "bedwars_getting_the_job_done_better",
                        "general_use_portal",
                        "bedwars_revenge",
                        "arcade_woops_didnt_mean_to",
                        "skyblock_your_adventure_begins",
                        "paintball_no_killstreaks",
                        "skyblock_your_big_break",
                        "skyblock_lost_soul",
                        "halloween2017_tricked",
                        "arcade_hoehoehoe_score",
                        "general_a_long_journey_begins",
                    ],
                    "stats": {
                        "HungerGames": {
                            "deaths": 6,
                            "coins": 210,
                            "packages": [
                                "fixachievements2",
                                "fixachievements1",
                                "used_kit_archer",
                                "used_kit_knight",
                                "new_stats_02_2019",
                                "fixachievements3",
                            ],
                            "arrows_fired": 14,
                            "arrows_fired_archer": 6,
                            "chests_opened": 12,
                            "chests_opened_archer": 5,
                            "damage": 25,
                            "damage_archer": 24,
                            "damage_taken": 122,
                            "damage_taken_archer": 84,
                            "games_played": 2,
                            "games_played_archer": 1,
                            "potions_drunk": 2,
                            "potions_drunk_archer": 2,
                            "time_played": 554,
                            "time_played_archer": 334,
                            "arrows_fired_knight": 8,
                            "chests_opened_knight": 7,
                            "damage_knight": 1,
                            "damage_taken_knight": 38,
                            "games_played_knight": 1,
                            "potions_thrown": 1,
                            "potions_thrown_knight": 1,
                            "time_played_knight": 220,
                            "wins_teams_normal": 0,
                            "wins_solo_normal": 0,
                            "wins_backup": 0,
                            "wins": 0,
                            "autoarmor": True,
                        },
                        "MCGO": {
                            "headshot_kills": 5,
                            "shots_fired": 115,
                            "deaths": 7,
                            "coins": 2549,
                            "round_wins": 3,
                            "bombs_planted": 0,
                            "game_wins_deathmatch": 0,
                            "packages": [
                                "achievement_flag_3",
                                "achievement_flag_4",
                                "achievement_flag_7",
                            ],
                            "game_wins": 0,
                            "kills_deathmatch": 0,
                            "bombs_defused": 0,
                            "kills": 1,
                            "deaths_deathmatch": 5,
                            "grenade_kills": 0,
                            "pocket_change": 0,
                            "grenadeKills": 0,
                            "cop_kills": 1,
                            "lastTourneyAd": 1585888062375,
                        },
                        "Arcade": {
                            "coins": 225032.0,
                            "dec2016_achievements2": True,
                            "dec2016_achievements": True,
                            "weekly_coins_b": 457,
                            "monthly_coins_a": 247,
                            "kills_dayone": 6,
                            "monthly_coins_b": 713,
                            "weekly_coins_a": 503,
                            "arrows_hit_mini_walls": 8,
                            "kills_mini_walls": 1,
                            "wins_mini_walls": 2,
                            "wither_kills_mini_walls": 2,
                            "deaths_mini_walls": 10,
                            "arrows_shot_mini_walls": 19,
                            "wither_damage_mini_walls": 55,
                            "music": False,
                            "final_kills_mini_walls": 1,
                            "rounds_simon_says": 12,
                            "sw_deaths": 9,
                            "sw_empire_kills": 12,
                            "sw_game_wins": 1,
                            "sw_kills": 12,
                            "sw_shots_fired": 521,
                            "lastTourneyAd": 1608016406065,
                        },
                        "GingerBread": {
                            "jacket_active": "GOLD_JACKET",
                            "engine_active": "{GingerbreadPart:{PartType" + ":ENGINE,PartRarity:BASIC}}",
                            "skin_active": "BLUE_KART;DEFAULT",
                            "booster_active": "{GingerbreadPart:{PartType" + ":TURBOCHARGER,PartRarity:BASIC}}",
                            "shoes_active": "GOLD_SHOES",
                            "pants_active": "GOLD_PANTS",
                            "frame_active": "{GingerbreadPart:{PartType:" + "FRAME,PartRarity:BASIC}}",
                            "packages": [
                                "helmet_1_3_unlocked",
                                "achievementsupdatedd",
                                "achievementsupdatedc",
                            ],
                            "helmet_active": "HELMET_1_3",
                            "coins": 15,
                            "horn": "DEFAULT",
                        },
                        "Paintball": {
                            "packages": ["achievement_flag_1", "achievement_flag_2"],
                            "coins": 991,
                            "deaths": 3,
                            "kills": 3,
                            "shots_fired": 116,
                            "wins": 1,
                        },
                        "Quake": {"packages": ["achievement_flag_3"], "coins": 15},
                        "VampireZ": {
                            "updated_stats": True,
                            "human_deaths": 3,
                            "coins": 256,
                            "vampire_deaths": 2,
                            "zombie_kills": 2,
                            "vampire_kills": 3,
                            "most_vampire_kills_new": 0,
                        },
                        "Legacy": {
                            "tokens_daily": 18,
                            "tokens_last_received_stamp": 1493276190648,
                            "next_tokens_seconds": 18,
                            "total_tokens": 24,
                            "vampirez_tokens": 13,
                            "tokens": 24,
                            "walls_tokens": 10,
                            "paintball_tokens": 1,
                        },
                        "Walls": {"losses": 1, "deaths": 1, "coins": 15},
                        "Bedwars": {
                            "packages": [
                                "tiered_achievement_flag_1",
                                "tiered_achievement_flag_2",
                                "islandtopper_tnt",
                                "glyph_sword",
                                "projectiletrail_purple_dust",
                                "v14_book",
                                "glyph_storm",
                                "npcskin_zombie_pigman",
                                "sprays_golem_riding",
                                "projectiletrail_red_dust",
                                "glyph_diamond",
                                "deathcry_bat",
                                "islandtopper_treasure_chest",
                                "glyph_yes",
                                "capture_book_0",
                                "glyph_iron",
                                "islandtopper_sword",
                                "glyph_emerald",
                                "sprays_diamond",
                                "killeffect_tnt",
                                "deathcry_plop",
                                "sprays_sorry",
                                "islandtopper_flame",
                                "glyph_thumbs_down",
                                "glyph_smiley_face",
                                "glyph_thumbs_up",
                                "sprays_surprise_snowball",
                                "glyph_christmas_tree",
                            ],
                            "first_join_7": True,
                            "Experience": 65262,
                            "bedwars_boxes": 4,
                            "games_played_bedwars_1": 422,
                            "winstreak": 0,
                            "final_deaths_bedwars": 294,
                            "gold_resources_collected_bedwars": 8471,
                            "four_four_beds_lost_bedwars": 125,
                            "four_four_losses_bedwars": 138,
                            "four_four_iron_resources_collected_bedwars": 31065,
                            "beds_lost_bedwars": 292,
                            "four_four_entity_attack_final_deaths_bedwars": 63,
                            "four_four__items_purchased_bedwars": 2425,
                            "four_four_games_played_bedwars": 179,
                            "diamond_resources_collected_bedwars": 2457,
                            "entity_attack_final_deaths_bedwars": 133,
                            "resources_collected_bedwars": 66335,
                            "losses_bedwars": 321,
                            "coins": 34821,
                            "items_purchased_bedwars": 4933,
                            "games_played_bedwars": 416,
                            "four_four_final_deaths_bedwars": 126,
                            "four_four_resources_collected_bedwars": 36933,
                            "four_four_items_purchased_bedwars": 2577,
                            "four_four_gold_resources_collected_bedwars": 4216,
                            "iron_resources_collected_bedwars": 54734,
                            "four_four_diamond_resources_collected_bedwars": 1418,
                            "_items_purchased_bedwars": 4652,
                            "deaths_bedwars": 1170,
                            "emerald_resources_collected_bedwars": 673,
                            "four_three_iron_resources_collected_bedwars": 15993,
                            "four_three_games_played_bedwars": 117,
                            "four_three__items_purchased_bedwars": 1372,
                            "permanent _items_purchased_bedwars": 267,
                            "four_three_emerald_resources_collected_bedwars": 317,
                            "four_three_entity_attack_deaths_bedwars": 156,
                            "four_three_gold_resources_collected_bedwars": 2814,
                            "four_three_permanent _items_purchased_bedwars": 78,
                            "four_three_deaths_bedwars": 407,
                            "four_three_losses_bedwars": 87,
                            "entity_attack_deaths_bedwars": 467,
                            "four_three_diamond_resources_collected_bedwars": 810,
                            "four_three_items_purchased_bedwars": 1454,
                            "four_three_resources_collected_bedwars": 19934,
                            "void_kills_bedwars": 177,
                            "four_four_void_kills_bedwars": 85,
                            "four_four_kills_bedwars": 136,
                            "kills_bedwars": 290,
                            "entity_attack_kills_bedwars": 105,
                            "four_four_entity_attack_kills_bedwars": 47,
                            "eight_one_items_purchased_bedwars": 63,
                            "eight_one_diamond_resources_collected_bedwars": 4,
                            "eight_one_games_played_bedwars": 8,
                            "eight_one_losses_bedwars": 7,
                            "eight_one_iron_resources_collected_bedwars": 453,
                            "eight_one_resources_collected_bedwars": 554,
                            "eight_one__items_purchased_bedwars": 62,
                            "eight_one_gold_resources_collected_bedwars": 97,
                            "four_four_emerald_resources_collected_bedwars": 234,
                            "void_deaths_bedwars": 654,
                            "four_four_deaths_bedwars": 458,
                            "four_four_void_final_deaths_bedwars": 60,
                            "void_final_deaths_bedwars": 147,
                            "four_four_void_deaths_bedwars": 270,
                            "four_three_beds_lost_bedwars": 81,
                            "four_three_void_final_deaths_bedwars": 47,
                            "four_three_final_deaths_bedwars": 82,
                            "four_four_permanent _items_purchased_bedwars": 142,
                            "fall_deaths_bedwars": 26,
                            "four_four_fall_deaths_bedwars": 9,
                            "four_four_entity_attack_deaths_bedwars": 175,
                            "bedwars_box_rares": 1,
                            "bedwars_box": 0,
                            "chest_history_new": [
                                "glyph_thumbs_up",
                                "islandtopper_flame",
                                "sprays_sorry",
                                "deathcry_plop",
                                "killeffect_tnt",
                            ],
                            "bedwars_box_commons": 2,
                            "spray_glyph_field": "SWORD,NONE,NONE,NONE,NONE,NONE",
                            "activeIslandTopper": "islandtopper_flame",
                            "activeProjectileTrail": "projectiletrail_purple_dust",
                            "four_three_wins_bedwars": 25,
                            "four_three_void_deaths_bedwars": 227,
                            "wins_bedwars": 79,
                            "four_four_wins_bedwars": 38,
                            "four_three_fall_deaths_bedwars": 12,
                            "eight_one_void_deaths_bedwars": 7,
                            "eight_one_deaths_bedwars": 16,
                            "four_four_beds_broken_bedwars": 9,
                            "beds_broken_bedwars": 29,
                            "entity_attack_final_kills_bedwars": 28,
                            "four_four_entity_attack_final_kills_bedwars": 13,
                            "final_kills_bedwars": 53,
                            "four_four_final_kills_bedwars": 20,
                            "four_three_void_kills_bedwars": 57,
                            "four_three_entity_attack_final_deaths_bedwars": 30,
                            "four_three_kills_bedwars": 95,
                            "four_four_projectile_final_kills_bedwars": 2,
                            "projectile_final_kills_bedwars": 2,
                            "eight_two_final_deaths_bedwars": 78,
                            "eight_two__items_purchased_bedwars": 663,
                            "eight_two_entity_attack_final_deaths_bedwars": 33,
                            "eight_two_games_played_bedwars": 87,
                            "eight_two_items_purchased_bedwars": 700,
                            "eight_two_resources_collected_bedwars": 7420,
                            "eight_two_beds_lost_bedwars": 78,
                            "eight_two_diamond_resources_collected_bedwars": 225,
                            "eight_two_gold_resources_collected_bedwars": 1213,
                            "eight_two_iron_resources_collected_bedwars": 5868,
                            "eight_two_losses_bedwars": 83,
                            "four_four_winstreak": 1,
                            "eight_two_winstreak": 0,
                            "eight_two_void_deaths_bedwars": 129,
                            "eight_two_emerald_resources_collected_bedwars": 114,
                            "eight_two_permanent _items_purchased_bedwars": 37,
                            "eight_two_wins_bedwars": 4,
                            "eight_two_kills_bedwars": 45,
                            "eight_two_entity_explosion_kills_bedwars": 1,
                            "eight_two_entity_attack_final_kills_bedwars": 9,
                            "eight_two_entity_attack_kills_bedwars": 18,
                            "eight_two_deaths_bedwars": 233,
                            "eight_two_entity_attack_deaths_bedwars": 99,
                            "entity_explosion_kills_bedwars": 2,
                            "eight_two_final_kills_bedwars": 19,
                            "four_three_winstreak": 3,
                            "eight_two_void_final_deaths_bedwars": 39,
                            "eight_two_fall_final_deaths_bedwars": 1,
                            "fall_final_deaths_bedwars": 4,
                            "eight_two_beds_broken_bedwars": 9,
                            "eight_two_void_kills_bedwars": 26,
                            "Bedwars_openedChests": 21,
                            "Bedwars_openedRares": 8,
                            "Bedwars_openedCommons": 14,
                            "activeNPCSkin": "npcskin_blacksmith",
                            "favourites_2": "wool,stone_sword,chainmail_boots"
                            + "wooden_axe,bow,speed_ii_potion_(45_seconds),tnt"
                            + "oak_wood_planks,iron_sword,iron_boots,shears,arrow"
                            + "invisibility_potion_(30_seconds),water_bucket"
                            + "end_stone,obsidian,null,null,null,wooden_pickaxe"
                            + "fireball",
                            "eight_one_winstreak": 0,
                            "eight_one_beds_lost_bedwars": 3,
                            "eight_one_final_deaths_bedwars": 3,
                            "eight_one_entity_attack_deaths_bedwars": 6,
                            "eight_one_beds_broken_bedwars": 2,
                            "eight_one_entity_attack_final_deaths_bedwars": 2,
                            "four_three_entity_attack_kills_bedwars": 36,
                            "Bedwars_openedEpics": 2,
                            "eight_one_permanent _items_purchased_bedwars": 1,
                            "eight_one_void_kills_bedwars": 2,
                            "eight_one_kills_bedwars": 2,
                            "eight_two_void_final_kills_bedwars": 9,
                            "void_final_kills_bedwars": 22,
                            "castle_items_purchased_bedwars": 7,
                            "castle_diamond_resources_collected_bedwars": 2,
                            "castle_deaths_bedwars": 2,
                            "castle_gold_resources_collected_bedwars": 3,
                            "castle__items_purchased_bedwars": 7,
                            "castle_resources_collected_bedwars": 29,
                            "castle_games_played_bedwars": 1,
                            "castle_wins_bedwars": 1,
                            "castle_void_deaths_bedwars": 2,
                            "castle_iron_resources_collected_bedwars": 24,
                            "castle_winstreak": 1,
                            "four_three_fall_final_deaths_bedwars": 2,
                            "four_four_projectile_deaths_bedwars": 2,
                            "projectile_deaths_bedwars": 5,
                            "activeDeathCry": "deathcry_bat",
                            "four_three_projectile_deaths_bedwars": 3,
                            "four_four_void_final_kills_bedwars": 5,
                            "four_three_beds_broken_bedwars": 8,
                            "four_three_entity_attack_final_kills_bedwars": 4,
                            "four_three_final_kills_bedwars": 12,
                            "four_three_void_final_kills_bedwars": 8,
                            "four_three_projectile_kills_bedwars": 1,
                            "projectile_kills_bedwars": 3,
                            "four_three_suffocation_deaths_bedwars": 1,
                            "suffocation_deaths_bedwars": 1,
                            "activeKillEffect": "killeffect_tnt",
                            "activeSprays": "sprays_surprise_snowball",
                            "activeGlyph": "glyph_christmas_tree",
                            "four_four_entity_explosion_kills_bedwars": 1,
                            "fall_kills_bedwars": 3,
                            "four_four_fall_kills_bedwars": 1,
                            "two_four_winstreak": 0,
                            "two_four__items_purchased_bedwars": 130,
                            "two_four_deaths_bedwars": 56,
                            "two_four_emerald_resources_collected_bedwars": 8,
                            "two_four_entity_attack_deaths_bedwars": 31,
                            "two_four_games_played_bedwars": 25,
                            "two_four_gold_resources_collected_bedwars": 131,
                            "two_four_iron_resources_collected_bedwars": 1355,
                            "two_four_items_purchased_bedwars": 139,
                            "two_four_losses_bedwars": 6,
                            "two_four_resources_collected_bedwars": 1494,
                            "two_four_void_deaths_bedwars": 21,
                            "eight_two_magic_final_deaths_bedwars": 4,
                            "magic_final_deaths_bedwars": 9,
                            "selected_ultimate": "DEMOLITION",
                            "eight_two_ultimate_winstreak": 0,
                            "eight_two_ultimate_beds_lost_bedwars": 2,
                            "eight_two_ultimate_final_deaths_bedwars": 2,
                            "eight_two_ultimate_games_played_bedwars": 2,
                            "eight_two_ultimate_gold_resources_collected_bedwars": 9,
                            "eight_two_ultimate_iron_resources_collected_bedwars": 42,
                            "eight_two_ultimate_kills_bedwars": 1,
                            "eight_two_ultimate_losses_bedwars": 2,
                            "eight_two_ultimate_resources_collected_bedwars": 51,
                            "eight_two_ultimate_void_final_deaths_bedwars": 2,
                            "eight_two_ultimate_void_kills_bedwars": 1,
                            "bedwars_easter_boxes": 3,
                            "free_event_key_bedwars_easter_boxes_2020": True,
                            "four_three_magic_deaths_bedwars": 7,
                            "magic_deaths_bedwars": 16,
                            "four_four_magic_final_deaths_bedwars": 2,
                            "eight_two_fall_final_kills_bedwars": 1,
                            "fall_final_kills_bedwars": 1,
                            "entity_explosion_deaths_bedwars": 1,
                            "four_three_entity_explosion_deaths_bedwars": 1,
                            "four_three_magic_final_deaths_bedwars": 3,
                            "eight_one_void_final_deaths_bedwars": 1,
                            "eight_two_fall_deaths_bedwars": 4,
                            "four_four_fall_final_deaths_bedwars": 1,
                            "four_four_magic_deaths_bedwars": 2,
                            "two_four_fall_kills_bedwars": 1,
                            "two_four_kills_bedwars": 12,
                            "two_four_wins_bedwars": 12,
                            "two_four_beds_broken_bedwars": 1,
                            "two_four_entity_attack_final_kills_bedwars": 2,
                            "two_four_final_kills_bedwars": 2,
                            "two_four_permanent _items_purchased_bedwars": 9,
                            "two_four_beds_lost_bedwars": 5,
                            "two_four_entity_attack_final_deaths_bedwars": 5,
                            "two_four_final_deaths_bedwars": 5,
                            "two_four_void_kills_bedwars": 7,
                            "two_four_magic_deaths_bedwars": 4,
                            "eight_one_fall_deaths_bedwars": 1,
                            "eight_one_magic_deaths_bedwars": 2,
                            "four_four_ultimate_winstreak": 0,
                            "four_four_ultimate__items_purchased_bedwars": 23,
                            "four_four_ultimate_beds_lost_bedwars": 2,
                            "four_four_ultimate_deaths_bedwars": 3,
                            "four_four_ultimate_diamond_resources_collected_bedwars": 3,
                            "four_four_ultimate_emerald_resources_collected_bedwars": 7,
                            "four_four_ultimate_entity_attack_kills_bedwars": 2,
                            "four_four_ultimate_final_deaths_bedwars": 2,
                            "four_four_ultimate_games_played_bedwars": 3,
                            "four_four_ultimate_gold_resources_collected_bedwars": 28,
                            "four_four_ultimate_iron_resources_collected_bedwars": 245,
                            "four_four_ultimate_items_purchased_bedwars": 27,
                            "four_four_ultimate_kills_bedwars": 2,
                            "four_four_ultimate_permanent _items_purchased_bedwars": 4,
                            "four_four_ultimate_resources_collected_bedwars": 283,
                            "four_four_ultimate_void_deaths_bedwars": 2,
                            "four_four_ultimate_void_final_deaths_bedwars": 1,
                            "four_four_ultimate_wins_bedwars": 1,
                            "four_four_ultimate_entity_attack_final_deaths_bedwars": 1,
                            "four_four_ultimate_losses_bedwars": 1,
                            "four_four_ultimate_magic_deaths_bedwars": 1,
                            "eight_two_magic_deaths_bedwars": 1,
                            "eight_two_fire_tick_final_deaths_bedwars": 1,
                            "fire_tick_final_deaths_bedwars": 1,
                            "four_three_fall_kills_bedwars": 1,
                            "two_four_entity_attack_kills_bedwars": 4,
                            "four_four_permanent_items_purchased_bedwars": 10,
                            "permanent_items_purchased_bedwars": 14,
                            "four_three_permanent_items_purchased_bedwars": 4,
                            "bedwars_christmas_boxes": 3,
                            "free_event_key_bedwars_christmas_boxes_2020": True,
                            "four_four_projectile_kills_bedwars": 2,
                            "quads_ultimate_kills_bedwars": 0,
                        },
                        "Walls3": {
                            "packages": [
                                "legacy_achievement_a",
                                "achievement_fix_flag",
                            ],
                            "chosen_class": "Skeleton",
                            "coins": 15,
                            "phoenix_total_deaths_standard": 8,
                            "phoenix_meters_walked": 1985,
                            "phoenix_blocks_placed_preparation": 7,
                            "iron_ore_broken_standard": 148,
                            "treasures_found_standard": 17,
                            "self_healed_standard": 10,
                            "phoenix_meters_walked_standard": 1985,
                            "food_eaten": 1,
                            "blocks_broken_standard": 753,
                            "potions_drunk_standard": 7,
                            "losses": 2,
                            "phoenix_arrows_fired_standard": 48,
                            "meters_walked_speed_standard": 95,
                            "phoenix_wood_chopped_standard": 4,
                            "phoenix_meters_walked_speed_standard": 40,
                            "phoenix_arrows_hit": 11,
                            "phoenix_blocks_placed_preparation_standard": 7,
                            "phoenix_games_played": 1,
                            "phoenix_iron_ore_broken": 52,
                            "phoenix_a_activations_standard": 5,
                            "total_deaths": 12,
                            "final_deaths_standard": 2,
                            "phoenix_total_deaths": 8,
                            "phoenix_arrows_fired": 48,
                            "losses_standard": 2,
                            "meters_walked": 2981,
                            "phoenix_treasures_found": 6,
                            "meters_fallen_standard": 705,
                            "phoenix_potions_drunk_standard": 6,
                            "phoenix_deaths_standard": 7,
                            "activations_standard": 6,
                            "potions_drunk": 7,
                            "treasures_found": 17,
                            "blocks_broken": 753,
                            "phoenix_time_played_standard": 15,
                            "self_healed": 10,
                            "wood_chopped": 4,
                            "phoenix_deaths": 7,
                            "activations": 6,
                            "blocks_placed": 33,
                            "phoenix_food_eaten": 1,
                            "arrows_fired_standard": 79,
                            "phoenix_final_deaths_standard": 1,
                            "phoenix_potions_drunk": 6,
                            "phoenix_wood_chopped": 4,
                            "meters_walked_speed": 95,
                            "phoenix_time_played": 15,
                            "phoenix_blocks_placed": 7,
                            "phoenix_amount_healed_standard": 3,
                            "phoenix_losses_standard": 1,
                            "arrows_fired": 79,
                            "phoenix_meters_fallen": 445,
                            "time_played": 27,
                            "iron_ore_broken": 148,
                            "phoenix_meters_fallen_standard": 445,
                            "deaths_standard": 10,
                            "total_deaths_standard": 12,
                            "phoenix_blocks_broken": 288,
                            "amount_healed": 10,
                            "wood_chopped_standard": 4,
                            "phoenix_iron_ore_broken_standard": 52,
                            "phoenix_self_healed": 3,
                            "phoenix_treasures_found_standard": 6,
                            "food_eaten_standard": 1,
                            "final_deaths": 2,
                            "phoenix_blocks_placed_standard": 7,
                            "games_played": 2,
                            "phoenix_final_deaths": 1,
                            "blocks_placed_standard": 33,
                            "blocks_placed_preparation": 25,
                            "phoenix_games_played_standard": 1,
                            "phoenix_food_eaten_standard": 1,
                            "arrows_hit_standard": 17,
                            "phoenix_self_healed_standard": 3,
                            "phoenix_activations": 5,
                            "meters_fallen": 705,
                            "amount_healed_standard": 10,
                            "phoenix_amount_healed": 3,
                            "phoenix_meters_walked_speed": 40,
                            "blocks_placed_preparation_standard": 25,
                            "phoenix_arrows_hit_standard": 11,
                            "phoenix_blocks_broken_standard": 288,
                            "meters_walked_standard": 2981,
                            "arrows_hit": 17,
                            "phoenix_losses": 1,
                            "phoenix_a_activations": 5,
                            "games_played_standard": 2,
                            "time_played_standard": 27,
                            "deaths": 10,
                            "phoenix_activations_standard": 5,
                            "zombie_blocks_broken": 465,
                            "zombie_total_deaths_standard": 4,
                            "energy_syphoned_standard": 24,
                            "zombie_amount_healed_standard": 7,
                            "zombie_a_self_healed_standard": 7,
                            "zombie_meters_fallen": 260,
                            "zombie_meters_fallen_standard": 260,
                            "zombie_final_deaths": 1,
                            "zombie_treasures_found": 11,
                            "zombie_blocks_placed_standard": 26,
                            "zombie_blocks_broken_standard": 465,
                            "zombie_deaths_standard": 3,
                            "zombie_arrows_fired_standard": 31,
                            "zombie_total_deaths": 4,
                            "zombie_blocks_placed": 26,
                            "zombie_time_played_standard": 12,
                            "bread_crafted": 6,
                            "zombie_energy_syphoned_standard": 24,
                            "zombie_time_played": 12,
                            "zombie_energy_syphoned": 24,
                            "zombie_iron_ore_broken": 96,
                            "zombie_bread_crafted": 6,
                            "bread_crafted_standard": 6,
                            "zombie_losses": 1,
                            "zombie_potions_drunk": 1,
                            "zombie_games_played": 1,
                            "zombie_activations_standard": 1,
                            "zombie_iron_ore_broken_standard": 96,
                            "zombie_meters_walked": 996,
                            "zombie_meters_walked_standard": 996,
                            "zombie_treasures_found_standard": 11,
                            "zombie_a_amount_healed_standard": 7,
                            "energy_syphoned": 24,
                            "zombie_games_played_standard": 1,
                            "zombie_blocks_placed_preparation_standard": 18,
                            "zombie_arrows_fired": 31,
                            "zombie_arrows_hit_standard": 6,
                            "zombie_final_deaths_standard": 1,
                            "zombie_a_self_healed": 7,
                            "zombie_a_activations_standard": 1,
                            "zombie_meters_walked_speed": 55,
                            "zombie_potions_drunk_standard": 1,
                            "zombie_activations": 1,
                            "zombie_self_healed_standard": 7,
                            "zombie_self_healed": 7,
                            "zombie_a_activations": 1,
                            "zombie_losses_standard": 1,
                            "zombie_deaths": 3,
                            "zombie_arrows_hit": 6,
                            "zombie_meters_walked_speed_standard": 55,
                            "zombie_blocks_placed_preparation": 18,
                            "zombie_amount_healed": 7,
                            "zombie_bread_crafted_standard": 6,
                            "zombie_a_amount_healed": 7,
                        },
                        "TNTGames": {
                            "coins": 362,
                            "new_tntag_speedy": 1,
                            "new_spleef_repulsor": 1,
                            "new_icewizard_regen": 1,
                            "new_bloodwizard_regen": 1,
                            "new_bloodwizard_explode": 1,
                            "packages": [
                                "tiered_achievement_flag_3",
                                "clicked_tnt_run_npc",
                                "clicked_tnt_tag_npc",
                                "shop_2018",
                            ],
                            "new_witherwizard_explode": 1,
                            "new_pvprun_double_jumps": 1,
                            "new_firewizard_explode": 1,
                            "wins": 0,
                            "new_spleef_tripleshot": 1,
                            "new_firewizard_regen": 1,
                            "new_tntrun_double_jumps": 1,
                            "new_icewizard_explode": 1,
                            "new_kineticwizard_regen": 1,
                            "new_kineticwizard_explode": 1,
                            "new_witherwizard_regen": 1,
                            "new_spleef_double_jumps": 1,
                            "run_potions_splashed_on_players": 0,
                            "record_tntrun": 78,
                            "deaths_tntrun": 3,
                            "winstreak": 0,
                            "flags": {
                                "show_tip_holograms": True,
                                "show_tntrun_actionbar_info": False,
                                "show_tnttag_actionbar_info": True,
                            },
                        },
                        "Arena": {"coins": 15},
                        "UHC": {"coins": 15},
                        "SkyWars": {
                            "coins": 747,
                            "souls": 10,
                            "activeKit_TEAMS": "kit_mining_team_default",
                            "activeKit_TEAMS_random": False,
                            "games_played_skywars": 2,
                            "win_streak": 0,
                            "lastMode": "TEAMS",
                            "losses_kit_mining_team_default": 1,
                            "blocks_placed": 2,
                            "losses_team_normal": 2,
                            "losses": 2,
                            "chests_opened_team": 4,
                            "survived_players_kit_mining_team_default": 19,
                            "time_played_team": 140,
                            "survived_players_team": 29,
                            "losses_team": 2,
                            "quits": 2,
                            "deaths_team_normal": 2,
                            "time_played_kit_mining_team_default": 83,
                            "survived_players": 29,
                            "chests_opened": 4,
                            "time_played": 140,
                            "deaths_team": 2,
                            "deaths_kit_mining_team_default": 1,
                            "deaths": 2,
                            "chests_opened_kit_mining_team_default": 2,
                            "skywars_chests": 1,
                            "levelFormatted": "§71⋆",
                            "packages": [
                                "update_solo_team_kits_and_perks",
                                "update_solo_team_kits2",
                                "update_solo_team_perk_levels",
                            ],
                            "blocks_broken": 10,
                            "chests_opened_kit_basic_solo_default": 2,
                            "deaths_kit_basic_solo_default": 1,
                            "losses_kit_basic_solo_default": 1,
                            "survived_players_kit_basic_solo_default": 10,
                            "time_played_kit_basic_solo_default": 57,
                        },
                        "TrueCombat": {
                            "packages": [
                                "cw_ach_flag1",
                                "cw_ach_flag4",
                                "cw_ach_flag2",
                                "cw_ach_flag3",
                            ]
                        },
                        "MurderMystery": {
                            "murdermystery_books": ["innocent"],
                            "detective_chance": 1,
                            "murderer_chance": 1,
                            "coins_pickedup_MURDER_CLASSIC": 3,
                            "wins": 1,
                            "games_ancient_tomb": 1,
                            "coins": 79,
                            "games_ancient_tomb_MURDER_CLASSIC": 1,
                            "wins_ancient_tomb_MURDER_CLASSIC": 1,
                            "coins_pickedup_ancient_tomb_MURDER_CLASSIC": 3,
                            "games": 1,
                            "games_MURDER_CLASSIC": 1,
                            "coins_pickedup": 3,
                            "coins_pickedup_ancient_tomb": 3,
                            "wins_MURDER_CLASSIC": 1,
                            "wins_ancient_tomb": 1,
                            "mm_christmas_chests": 1,
                        },
                        "SkyClash": {"card_packs": 1},
                        "Battleground": {
                            "warrior_spec": "berserker",
                            "packages": [
                                "legacyachievement9",
                                "legacyachievement8",
                                "legacyachievement2",
                            ],
                            "selected_mount": "noble_steed",
                            "shaman_spec": "thunderlord",
                            "mage_spec": "pyromancer",
                            "paladin_spec": "avenger",
                            "chosen_class": "mage",
                            "hotkeymode": True,
                            "autostrikemode": False,
                        },
                        "Duels": {
                            "deaths": 1,
                            "bridge_2v2v2v2_losses": 1,
                            "bridge_2v2v2v2_rounds_played": 1,
                            "losses": 2,
                            "bridge_2v2v2v2_deaths": 1,
                            "rounds_played": 6,
                            "show_lb_option": "on",
                            "games_played_duels": 5,
                            "chat_enabled": "on",
                            "damage_dealt": 40,
                            "health_regenerated": 13,
                            "melee_hits": 11,
                            "melee_swings": 49,
                            "uhc_doubles_damage_dealt": 1,
                            "uhc_doubles_health_regenerated": 3,
                            "uhc_doubles_melee_hits": 1,
                            "uhc_doubles_melee_swings": 11,
                            "uhc_doubles_rounds_played": 1,
                            "op_rookie_title_prestige": 1,
                            "classic_rookie_title_prestige": 1,
                            "skywars_rookie_title_prestige": 1,
                            "sumo_rookie_title_prestige": 1,
                            "combo_rookie_title_prestige": 1,
                            "bow_rookie_title_prestige": 1,
                            "bridge_rookie_title_prestige": 1,
                            "no_debuff_rookie_title_prestige": 1,
                            "mega_walls_rookie_title_prestige": 1,
                            "blitz_rookie_title_prestige": 1,
                            "uhc_rookie_title_prestige": 1,
                            "all_modes_rookie_title_prestige": 1,
                            "tnt_games_rookie_title_prestige": 1,
                            "selected_2_new": "blitz",
                            "selected_1_new": "sumo",
                            "duels_recently_played2": "BRIDGE_FOUR#BRIDGE" + "_2V2V2V2#BRIDGE_DOUBLES",
                            "current_winstreak": 0,
                            "current_bridge_winstreak": 0,
                            "current_winstreak_mode_bridge_four": 0,
                            "bridge_deaths": 1,
                            "bridge_four_bridge_deaths": 1,
                            "bridge_four_losses": 1,
                            "bridge_four_rounds_played": 1,
                            "bridge_duel_rounds_played": 3,
                            "blocks_placed": 130,
                            "bow_hits": 2,
                            "bow_shots": 2,
                            "bridge_duel_blocks_placed": 130,
                            "bridge_duel_bow_hits": 2,
                            "bridge_duel_bow_shots": 2,
                            "bridge_duel_damage_dealt": 39,
                            "bridge_duel_health_regenerated": 10,
                            "bridge_duel_melee_hits": 10,
                            "bridge_duel_melee_swings": 38,
                        },
                        "BuildBattle": {
                            "coins": 516,
                            "games_played": 3,
                            "monthly_coins_b": 516,
                            "score": 30,
                            "teams_most_points": 85,
                            "total_votes": 24,
                            "weekly_coins_b": 516,
                        },
                        "Pit": {
                            "profile": {
                                "moved_achievements_1": True,
                                "outgoing_offers": [],
                                "moved_achievements_2": True,
                                "leaderboard_stats": {},
                                "last_save": 1589104356905,
                                "king_quest": {"kills": 1},
                                "inv_armor": {
                                    "type": 0,
                                    "data": [
                                        31,
                                        -117,
                                        8,
                                        0,
                                        0,
                                        0,
                                        0,
                                        0,
                                        0,
                                        0,
                                        -29,
                                        98,
                                        96,
                                        -32,
                                        100,
                                        96,
                                        -52,
                                        -28,
                                        98,
                                        96,
                                        96,
                                        96,
                                        97,
                                        98,
                                        96,
                                        -54,
                                        76,
                                        97,
                                        52,
                                        100,
                                        100,
                                        96,
                                        117,
                                        -50,
                                        47,
                                        -51,
                                        43,
                                        97,
                                        -28,
                                        98,
                                        96,
                                        46,
                                        73,
                                        76,
                                        103,
                                        100,
                                        -32,
                                        14,
                                        -51,
                                        75,
                                        42,
                                        74,
                                        77,
                                        -52,
                                        78,
                                        76,
                                        -54,
                                        73,
                                        101,
                                        100,
                                        96,
                                        98,
                                        96,
                                        115,
                                        73,
                                        -52,
                                        77,
                                        76,
                                        79,
                                        5,
                                        106,
                                        -127,
                                        -24,
                                        48,
                                        32,
                                        89,
                                        -121,
                                        49,
                                        9,
                                        58,
                                        24,
                                        24,
                                        0,
                                        70,
                                        -74,
                                        77,
                                        -75,
                                        -92,
                                        0,
                                        0,
                                        0,
                                    ],
                                },
                                "login_messages": [],
                                "spire_stash_inv": {
                                    "type": 0,
                                    "data": [
                                        31,
                                        -117,
                                        8,
                                        0,
                                        0,
                                        0,
                                        0,
                                        0,
                                        0,
                                        0,
                                        -29,
                                        98,
                                        96,
                                        -32,
                                        100,
                                        96,
                                        -52,
                                        100,
                                        0,
                                        3,
                                        0,
                                        -58,
                                        2,
                                        -70,
                                        27,
                                        13,
                                        0,
                                        0,
                                        0,
                                    ],
                                },
                                "inv_contents": {
                                    "type": 0,
                                    "data": [
                                        31,
                                        -117,
                                        8,
                                        0,
                                        0,
                                        0,
                                        0,
                                        0,
                                        0,
                                        0,
                                        -29,
                                        98,
                                        96,
                                        -32,
                                        100,
                                        96,
                                        -52,
                                        -28,
                                        98,
                                        96,
                                        96,
                                        80,
                                        97,
                                        98,
                                        96,
                                        -54,
                                        76,
                                        97,
                                        100,
                                        101,
                                        100,
                                        96,
                                        117,
                                        -50,
                                        47,
                                        -51,
                                        43,
                                        97,
                                        -28,
                                        98,
                                        96,
                                        46,
                                        73,
                                        76,
                                        103,
                                        100,
                                        -32,
                                        14,
                                        -51,
                                        75,
                                        42,
                                        74,
                                        77,
                                        -52,
                                        78,
                                        76,
                                        -54,
                                        73,
                                        101,
                                        100,
                                        96,
                                        98,
                                        96,
                                        115,
                                        73,
                                        -52,
                                        77,
                                        76,
                                        79,
                                        5,
                                        106,
                                        -127,
                                        -24,
                                        -32,
                                        38,
                                        65,
                                        7,
                                        4,
                                        64,
                                        -12,
                                        -79,
                                        -63,
                                        -12,
                                        41,
                                        96,
                                        -86,
                                        -64,
                                        14,
                                        0,
                                        96,
                                        50,
                                        47,
                                        -5,
                                        -82,
                                        0,
                                        0,
                                        0,
                                    ],
                                },
                                "xp": 527,
                                "zero_point_three_gold_transfer": True,
                                "inv_enderchest": {
                                    "type": 0,
                                    "data": [
                                        31,
                                        -117,
                                        8,
                                        0,
                                        0,
                                        0,
                                        0,
                                        0,
                                        0,
                                        0,
                                        -29,
                                        98,
                                        96,
                                        -32,
                                        100,
                                        96,
                                        -52,
                                        -28,
                                        98,
                                        96,
                                        96,
                                        -112,
                                        102,
                                        -64,
                                        3,
                                        0,
                                        -47,
                                        59,
                                        -26,
                                        15,
                                        40,
                                        0,
                                        0,
                                        0,
                                    ],
                                },
                                "bounties": [],
                                "spire_stash_armor": {
                                    "type": 0,
                                    "data": [
                                        31,
                                        -117,
                                        8,
                                        0,
                                        0,
                                        0,
                                        0,
                                        0,
                                        0,
                                        0,
                                        -29,
                                        98,
                                        96,
                                        -32,
                                        100,
                                        96,
                                        -52,
                                        100,
                                        0,
                                        3,
                                        0,
                                        -58,
                                        2,
                                        -70,
                                        27,
                                        13,
                                        0,
                                        0,
                                        0,
                                    ],
                                },
                                "cash": 572.0099999999999,
                                "cash_during_prestige_0": 572.0099999999999,
                            },
                            "pit_stats_ptl": {
                                "arrow_hits": 3,
                                "arrows_fired": 13,
                                "assists": 3,
                                "bow_damage_dealt": 9,
                                "bow_damage_received": 21,
                                "cash_earned": 18,
                                "damage_dealt": 16,
                                "damage_received": 88,
                                "deaths": 4,
                                "ingots_cash": 1,
                                "ingots_picked_up": 1,
                                "joins": 1,
                                "jumped_into_pit": 3,
                                "kills": 1,
                                "launched_by_launchers": 1,
                                "left_clicks": 21,
                                "max_streak": 1,
                                "melee_damage_dealt": 7,
                                "melee_damage_received": 67,
                                "sword_hits": 2,
                            },
                        },
                        "SkyBlock": {
                            "profiles": {
                                "405dcf08b80f4e23b97d943ad93d14fd": {
                                    "profile_id": "405dcf08b80f4e23b97d943ad93d14fd",
                                    "cute_name": "Strawberry",
                                }
                            }
                        },
                    },
                    "mcVersionRp": "1.15.2",
                    "achievements": {
                        "copsandcrims_hero_terrorist": 0,
                        "copsandcrims_serial_killer": 1,
                        "copsandcrims_bomb_specialist": 0,
                        "quake_coins": 0,
                        "quake_wins": 0,
                        "vampirez_zombie_killer": 0,
                        "paintball_kills": 3,
                        "quake_kills": 0,
                        "paintball_wins": 1,
                        "vampirez_coins": 241,
                        "general_coins": 4661,
                        "vampirez_kill_vampires": 3,
                        "arcade_miniwalls_winner": 2,
                        "arcade_arcade_banker": 4366,
                        "arcade_zombie_killer": 6,
                        "general_challenger": 77,
                        "bedwars_level": 15,
                        "bedwars_wins": 79,
                        "bedwars_loot_box": 10,
                        "bedwars_beds": 29,
                        "arcade_arcade_winner": 3,
                        "walls3_wins": 0,
                        "walls3_kills": 0,
                        "blitz_wins": 0,
                        "blitz_war_veteran": 0,
                        "blitz_wins_teams": 0,
                        "buildbattle_buildbattle_points": 42,
                        "skywars_cages": 1,
                        "bedwars_collectors_edition": 226,
                        "bedwars_bedwars_killer": 97,
                        "tntgames_tnt_banker": 347,
                        "tntgames_tnt_triathlon": 13,
                        "general_wins": 3,
                        "murdermystery_wins_as_survivor": 1,
                        "skyclash_cards_unlocked": 6,
                        "copsandcrims_headshot_kills": 10,
                        "blitz_looter": 12,
                        "buildbattle_build_battle_voter": 24,
                        "buildbattle_build_battle_points": 85,
                        "buildbattle_build_battle_score": 30,
                        "tntgames_block_runner": 716,
                        "copsandcrims_cac_banker": 25,
                        "arena_climb_the_ranks": 2000,
                        "gingerbread_banker": 15,
                        "pit_gold": 15,
                        "pit_kills": 1,
                        "skyblock_treasury": 12,
                        "skyblock_minion_lover": 4,
                        "paintball_coins": 976,
                        "summer_shopaholic": 244,
                        "skyblock_gatherer": 2,
                        "skyblock_excavator": 6,
                        "halloween2017_pumpkinator": 5,
                        "christmas2017_advent_2020": 6,
                        "christmas2017_present_collector": 75,
                        "general_quest_master": 1,
                    },
                    "networkExp": 514642.0,
                    "levelingReward_0": True,
                    "karma": 975,
                    "petConsumables": {
                        "CARROT_ITEM": 48,
                        "COOKIE": 34,
                        "SLIME_BALL": 119,
                        "CAKE": 33,
                        "RAW_FISH": 37,
                        "WATER_BUCKET": 217,
                        "STICK": 105,
                        "WOOD_SWORD": 118,
                        "MILK_BUCKET": 233,
                        "GOLD_RECORD": 110,
                        "PORK": 30,
                        "LEASH": 98,
                        "LAVA_BUCKET": 224,
                        "BONE": 44,
                        "MAGMA_CREAM": 44,
                        "MUSHROOM_SOUP": 31,
                        "BAKED_POTATO": 35,
                        "FEATHER": 115,
                        "ROTTEN_FLESH": 28,
                        "COOKED_BEEF": 41,
                        "RED_ROSE": 45,
                        "WHEAT": 35,
                        "HAY_BLOCK": 29,
                        "MELON": 33,
                        "PUMPKIN_PIE": 31,
                        "APPLE": 40,
                        "BREAD": 50,
                    },
                    "vanityMeta": {
                        "packages": [
                            "pet_wolf",
                            "taunt_cool_dance",
                            "hat_letter_n",
                            "suit_arctic_boots",
                            "hat_ferret",
                            "hat_letter_b",
                            "suit_necromancer_boots",
                            "emote_wink",
                            "emote_surprised",
                            "emote_dizzy",
                            "suit_soccer_boots",
                            "hat_penguin",
                            "pet_pig",
                            "hat_letter_m",
                            "hat_letter_k",
                            "gadget_fortune_cookie",
                            "suit_bumblebee_boots",
                            "gadget_ghosts",
                            "suit_flash_boots",
                            "taunt_goodbye",
                            "pet_horse_white",
                            "hat_mars",
                            "suit_dragon_breath_leggings",
                            "suit_solar_leggings",
                            "emote_heart",
                            "suit_plumber_leggings",
                            "hat_earth",
                            "emote_grin",
                            "suit_disco_boots",
                            "suit_warrior_boots",
                            "pet_sheep_silver",
                            "gadget_exploding_sheep",
                            "hat_letter_l",
                            "suit_disco_leggings",
                            "pet_cow",
                            "hat_letter_j",
                            "hat_letter_v",
                            "suit_chicken_leggings",
                            "hat_lady_bug",
                            "suit_chicken_boots",
                            "cloak_easter_egg",
                            "gadget_paintball_gun",
                            "hat_number_7",
                            "pet_sheep_green",
                            "pet_sheep_cyan",
                            "suit_wolf_leggings",
                            "hat_festive_zombie",
                            "hat_festive_skeleton",
                            "pet_frozen_zombie",
                            "hat_festive_villager",
                            "suit_frog_boots",
                        ]
                    },
                    "spec_always_flying": True,
                    "lastAdsenseGenerateTime": 1607152278977,
                    "eugene": {"dailyTwoKExp": 1607152814287},
                    "voting": {
                        "total": 3,
                        "total_mcsorg": 3,
                        "secondary_mcsorg": 3,
                        "last_mcsorg": 1565160548520,
                        "last_vote": 1565160548520,
                        "votesToday": 1,
                    },
                    "lastClaimedReward": 1.565160462479e12,
                    "totalRewards": 3,
                    "totalDailyRewards": 3,
                    "rewardStreak": 1,
                    "rewardScore": 1,
                    "rewardHighScore": 1,
                    "levelingReward_1": True,
                    "quickjoin_timestamp": 1602224495226,
                    "quickjoin_uses": 17,
                    "lastLogout": 1608016811099,
                    "levelingReward_2": True,
                    "levelingReward_3": True,
                    "levelingReward_4": True,
                    "friendRequestsUuid": [],
                    "network_update_book": "v0.73",
                    "levelingReward_5": True,
                    "challenges": {
                        "all_time": {
                            "BEDWARS__support": 58,
                            "BUILD_BATTLE__top_3_challenge": 1,
                            "DUELS__feed_the_void_challenge": 1,
                        }
                    },
                    "achievementTracking": [],
                    "petStats": {
                        "WOLF": {
                            "HUNGER": {"timestamp": 1529225265831, "value": 100},
                            "EXERCISE": {"value": 100, "timestamp": 1529225256120},
                            "THIRST": {"timestamp": 1529225262979, "value": 100},
                            "experience": 212,
                            "name": "Wolfy",
                        },
                    },
                    "parkourCheckpointBests": {"Bedwars": {"0": 11553, "1": 7949, "2": 11109, "3": 76136}},
                    "achievementSync": {"quake_tiered": 1},
                    "achievementRewardsNew": {
                        "for_points_200": 1530832841537,
                        "for_points_300": 1565170080092,
                        "for_points_400": 1584088556947,
                        "for_points_500": 1589445357967,
                    },
                    "levelingReward_6": True,
                    "achievementPoints": 640,
                    "housingMeta": {
                        "firstHouseJoinMs": 1557910244464,
                        "tutorialStep": "WAITING_FOR_INTERACTION",
                        "packages": [
                            "specialoccasion_reward_card_skull_pot_o\u0027_gold",
                            "day_at_the_beach_theme",
                            "migrated_to_mongo",
                            "specialoccasion_christmas_skull_yellow_ornament",
                        ],
                        "plotSize": "SMALL",
                    },
                    "levelingReward_7": True,
                    "levelingReward_8": True,
                    "levelingReward_9": True,
                    "currentGadget": "FORTUNE_COOKIE",
                    "levelingReward_10": True,
                    "channel": "ALL",
                    "levelingReward_11": True,
                    "parkourCompletions": {
                        "Bedwars": [
                            {"timeStart": 1565426292867, "timeTook": 202166},
                            {"timeStart": 1585102417335, "timeTook": 262259},
                            {"timeStart": 1589008710797, "timeTook": 143596},
                        ]
                    },
                    "monthlycrates": {
                        "5-2017": {"REGULAR": True},
                        "6-2018": {"REGULAR": True},
                        "6-2019": {"REGULAR": True},
                        "8-2017": {"REGULAR": True},
                        "8-2019": {"REGULAR": True},
                        "4-2020": {"REGULAR": True},
                        "5-2020": {"REGULAR": True},
                        "6-2020": {"REGULAR": True},
                        "9-2020": {"REGULAR": True},
                        "10-2020": {"REGULAR": True},
                        "12-2020": {"REGULAR": True},
                    },
                    "levelingReward_12": True,
                    "levelingReward_13": True,
                    "easter2020Cooldowns2": {
                        "NORMAL2": True,
                        "NORMAL1": True,
                        "NORMAL0": True,
                        "NORMAL3": True,
                    },
                    "levelingReward_14": True,
                    "levelingReward_15": True,
                    "levelingReward_16": True,
                    "summer2020Cooldowns": {"NORMAL0": True},
                    "halloween2020Cooldowns": {"NORMAL0": True},
                    "mostRecentGameType": "BEDWARS",
                    "christmas2020Cooldowns2": {"NORMAL0": True, "NORMAL1": True},
                    "adventRewards2020": {
                        "day1": 1607152263308,
                        "day2": 1607152268058,
                        "day5": 1607152275026,
                        "day7": 1607317543465,
                        "day9": 1607501776018,
                        "day15": 1608016441274,
                    },
                    "quests": {
                        "bedwars_daily_gifts": {
                            "completions": [{"time": 1607243208862}],
                            "active": {"objectives": {}, "started": 1607317857317},
                        }
                    },
                    "completed_christmas_quests_2020": 1,
                },
            },
        )
        data = None
        async for client in hypixel_client:
            data = await client.player("405dcf08-b80f-4e23-b97d-943ad93d14fd")

        assert data is not None
        assert data.id == "55e96b45de314c0f0424dc9a"
        assert data.uuid == uuid.UUID("405dcf08-b80f-4e23-b97d-943ad93d14fd")
        assert data.first_login == datetime.datetime.fromtimestamp(1441360709.245, tz=datetime.timezone.utc)
        assert data.playername == "darkflame72"
        assert data.last_login == datetime.datetime.fromtimestamp(1608016405.945, tz=datetime.timezone.utc)
        assert data.displayname == "Darkflame72"
        assert data.known_aliases == ["MRL03", "Darkflame72"]
        assert data.known_aliases_lower == ["mrl03", "darkflame72"]
        assert data.achievements_one_time == [
            "general_first_join",
            "blitz_first_game",
            "general_first_game",
            "general_first_chat",
            "vampirez_vampire_shop",
            "vampirez_close_call",
            "general_youtuber",
            "bedwars_team_player",
            "bedwars_builder",
            "bedwars_pickaxe_challenge",
            "bedwars_already_over",
            "bedwars_survivor",
            "bedwars_ultimate_defense",
            "bedwars_emerald_hoarder",
            "bedwars_first",
            "bedwars_geared_up",
            "bedwars_diamond_hoarder",
            "bedwars_sniper",
            "bedwars_dont_need_bed",
            "skywars_max_perk",
            "skywars_legendary",
            "walls3_happy",
            "walls3_find_chest",
            "bedwars_its_dark_down_there",
            "bedwars_thats_a_first",
            "vampirez_purchase_armor",
            "bedwars_buggy_beds",
            "tntgames_bow_spleef_first_double_jump",
            "murdermystery_soldiers_eliminated",
            "bedwars_first_blood",
            "general_first_party",
            "easter_happy_easter_2019",
            "housing_join_guild",
            "bedwars_minefield",
            "bedwars_savvy_shopper",
            "bedwars_you_cant_do_that",
            "general_first_friend",
            "bedwars_katniss_everdeen_style",
            "bedwars_rejoining_the_dream",
            "bedwars_super_looter",
            "blitz_safety_first",
            "bedwars_strategist",
            "bedwars_out_of_stock",
            "bedwars_distraction",
            "general_creeperbook",
            "arcade_pig_fishing_super_bacon",
            "arcade_professional_mower",
            "bedwars_shear_luck",
            "copsandcrims_late_to_the_party",
            "copsandcrims_sneak_kill",
            "bedwars_destroy_beds",
            "bedwars_getting_the_job_done_better",
            "general_use_portal",
            "bedwars_revenge",
            "arcade_woops_didnt_mean_to",
            "skyblock_your_adventure_begins",
            "paintball_no_killstreaks",
            "skyblock_your_big_break",
            "skyblock_lost_soul",
            "halloween2017_tricked",
            "arcade_hoehoehoe_score",
            "general_a_long_journey_begins",
        ]
        assert data.mc_version_rp == "1.15.2"
        assert data.network_exp == 514642.0
        assert data.karma == 975
        assert data.last_adsense_generate_time == datetime.datetime.fromtimestamp(
            1607152278.977, tz=datetime.timezone.utc
        )
        assert data.last_claimed_reward == 1.565160462479e12
        assert data.total_rewards == 3
        assert data.total_daily_rewards == 3
        assert data.reward_streak == 1
        assert data.reward_score == 1
        assert data.reward_high_score == 1
        assert data.last_logout == datetime.datetime.fromtimestamp(1608016811.099, tz=datetime.timezone.utc)
        assert data.friend_requests_uuid == []
        assert data.achievement_tracking == []
        assert data.achievement_points == 640
        assert data.current_gadget == "FORTUNE_COOKIE"
        assert data.channel == "ALL"
        assert data.level == 18.090376392868585

        assert data.stats.bedwars is not None
        assert data.stats.bedwars.experience == 65262
        assert data.stats.bedwars.level == 15.6524
        assert data.raw["achievements"]["bedwars_level"] == int(data.stats.bedwars.level)
        assert data.stats.bedwars.singles is not None
        assert data.stats.bedwars.singles.win_per_lose == 0.0
        assert data.stats.bedwars.singles.beds_broken_per_lost == 2 / 3
        assert data.stats.bedwars.singles.final_kills_per_final_death == 0
        assert data.stats.bedwars.final_kills_per_final_death == 0.18027210884353742
        assert data.stats.bedwars.beds_broken_per_lost == 0.09931506849315068
        assert data.stats.bedwars.win_lose == 0.24610591900311526
        assert data.stats.bedwars.level == 15.6524
        assert data.stats.skywars is not None
        assert data.stats.skywars.kills_per_death == 0.0
        assert data.stats.skywars.wins_per_lose == 0.0
        assert data.social_media is not None
        assert data.social_media.twitter == "https://twitter.com/hypixel"
        assert data.most_recent_game_type == GameType(
            id=58,
            type_name="BEDWARS",
            database_name="Bedwars",
            lobby_name="bedwars",
            clean_name="Bed Wars",
            standard_name="BedWars",
        )
        assert data.stats.bedwars.quads_ultimate is not None
        assert data.stats.bedwars.doubles_ultimate is None

        assert data.pet_stats is not None
        assert len(data.pet_stats) == 1
        assert data.pet_stats["WOLF"] is not None
        print(data.pet_stats)
        assert data.pet_stats["WOLF"].experience == 212
        assert data.pet_stats["WOLF"].name == "Wolfy"
        assert data.pet_stats["WOLF"].hunger is not None
        assert data.pet_stats["WOLF"].hunger.value == 100
        assert data.pet_stats["WOLF"].hunger.timestamp == datetime.datetime.fromtimestamp(
            1529225265.831, tz=datetime.timezone.utc
        )
        assert data.pet_stats["WOLF"].thirst is not None
        assert data.pet_stats["WOLF"].thirst.value == 100
        assert data.pet_stats["WOLF"].thirst.timestamp == datetime.datetime.fromtimestamp(
            1529225262.979, tz=datetime.timezone.utc
        )
        assert data.pet_stats["WOLF"].exercise is not None
        assert data.pet_stats["WOLF"].exercise.value == 100
        assert data.pet_stats["WOLF"].exercise.timestamp == datetime.datetime.fromtimestamp(
            1529225256.120, tz=datetime.timezone.utc
        )


@pytest.mark.asyncio
async def test_most_recent_game_type() -> None:
    """Test most recent game type."""
    assert validate_game_type(58) == GameType(
        id=58,
        type_name="BEDWARS",
        database_name="Bedwars",
        lobby_name="bedwars",
        clean_name="Bed Wars",
        standard_name="BedWars",
    )


@pytest.mark.asyncio
async def test_player_none(hypixel_client: AsyncGenerator[Hypixel, None], key: uuid.UUID) -> None:
    """Test to check the player method returns correct data when not found."""
    with aioresponses() as m:
        m.get(
            f"https://api.hypixel.net/player?key={key!s}" + "&uuid=405dcf08-b80f-4e23-b97d-943ad93d14fd",
            status=200,
            headers={
                "RateLimit-Limit": "120",
                "RateLimit-Remaining": "119",
                "RateLimit-Reset": "8",
            },
            payload={"success": True, "player": None},
        )
        data = None
        async for client in hypixel_client:
            data = await client.player("405dcf08-b80f-4e23-b97d-943ad93d14fd")

        assert data is None


def test_bedwars_level_calculation() -> None:
    """Test the bedwars level calculator against known values."""
    bw_star_data = [
        (500, 1),
        (89025, 20 + 2025 / 5000),
        (122986, 27),
        (954638, 196),
        (969078, 199),
        (975611, 202),
        (977587, 203),
        (2344717, 481 + 4717 / 5000),
    ]
    for exp, true_star in bw_star_data:
        calculated_star = bedwars_level_from_exp(exp)

        # Compare int with int, and float with float
        calculated_star = int(calculated_star)
        true_star = int(true_star)

        assert true_star == calculated_star, f"exp={exp}: calculated star={calculated_star}, true star={true_star}"


def test_safe_divide() -> None:
    """Test the safe divide utility."""
    test_cases = [
        (500, 1, 500.0),
        (-100, 2, -50.0),
        (100, 13, 100 / 13),
        (0, 0.5, 0.0),
        (100, 0, float("inf")),
        (0, 0, float("inf")),
        (-1.0, 0, float("-inf")),
    ]

    for dividend, divisor, quotient in test_cases:
        assert safe_divide(dividend, divisor) == quotient
        assert isinstance(safe_divide(dividend, divisor), float)
