name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

# Declare default permissions as read only.
permissions: read-all

concurrency:
  group: ${{ github.event.number || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
        with:
          submodules: "recursive"
      - name: Set up PDM
        uses: pdm-project/setup-pdm@f668fde1b040b5e7b36a100b0f35e34e2d37d0c3 # v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pdm sync -d -G style

      - name: Run Lint
        run: |
          pdm run -v lint

  tests:
    name: ${{ matrix.python-version }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", 3.11]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
        with:
          submodules: "recursive"

      - name: Set up PDM
        uses: pdm-project/setup-pdm@f668fde1b040b5e7b36a100b0f35e34e2d37d0c3 # v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pdm sync -d -G test

      - name: Run Tests
        run: |
          pdm run -v test

      - name: Upload coverage data
        uses: "actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce" # v3.1.2
        with:
          name: coverage-data
          path: ".coverage.*"

  coverage:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
        with:
          submodules: "recursive"
      - name: Set up PDM
        uses: pdm-project/setup-pdm@f668fde1b040b5e7b36a100b0f35e34e2d37d0c3 # v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pdm sync -d -G test

      - name: Download coverage data
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: coverage-data

      - name: Combine coverage and generate report
        run: |
          pdm run -v coverage_report

      - name: Generate coverage report
        run: |
          pdm run -v coverage -- xml

      - name: Upload coverage report
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
