name: Publish to PyPI

on:
  push:
    tags:
      - "*"
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: "Build dists"
    runs-on: "ubuntu-latest"
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@7739b9ba2efcda9dde65ad1e3c2dbe65b41dfba7"
        with:
          submodules: "recursive"

      - name: Set up PDM
        uses: pdm-project/setup-pdm@f668fde1b040b5e7b36a100b0f35e34e2d37d0c3 # v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pdm install

      - name: "Build dists"
        run: |
          pdm build

      - name: "Generate hashes"
        id: hash
        run: |
          cd dist && echo "::set-output name=hashes::$(sha256sum * | base64 -w0)"

      - name: "Upload dists"
        uses: "actions/upload-artifact@65d862660abb392b8c4a3d1195a2108db131dd05"
        with:
          name: "dist"
          path: "dist/"
          if-no-files-found: error
          retention-days: 5

  provenance:
    needs: [build]
    permissions:
      actions: read
      contents: write
      id-token: write # Needed to access the workflow's OIDC identity.
    uses: "slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@e55b76ce421082dfa4b34a6ac3c5e59de0f3bb58" # v1.7.0
    with:
      base64-subjects: "${{ needs.build.outputs.hashes }}"
      upload-assets: true

  publish-pypi-test:
    name: "Publish test"
    needs: ["build", "provenance"]
    permissions:
      id-token: write # Needed for trusted publishing to PyPI.
    runs-on: "ubuntu-latest"
    environment:
      name: "publish-test"
    steps:
      - name: "Download dists"
        uses: "actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a"
        with:
          name: "dist"
          path: "dist/"

      - name: "Publish dists to Test PyPI"
        uses: pypa/gh-action-pypi-publish@f8c70e705ffc13c3b4d1221169b84f12a75d6ca8
        with:
          repository-url: https://test.pypi.org/legacy/

  publish-pypi:
    name: "Publish"
    if: startsWith(github.ref, 'refs/tags/')
    needs: ["build", "provenance", "publish-pypi-test"]
    permissions:
      id-token: write # Needed for trusted publishing to PyPI.
    runs-on: "ubuntu-latest"
    environment:
      name: "publish"

    steps:
      - name: "Download dists"
        uses: "actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a"
        with:
          name: "dist"
          path: "dist/"

      - name: "Upload dists to GitHub Release"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          gh release upload ${{ github.ref_name }} dist/* --repo ${{ github.repository }}

      - name: "Publish dists to PyPI"
        uses: "pypa/gh-action-pypi-publish@f8c70e705ffc13c3b4d1221169b84f12a75d6ca8" # v1.8.8
